// Mapping of emoji and service IDs to Lucide icons
import {
  Pill,
  BarChart3,
  ClipboardList,
  Plane,
  User,
  GraduationCap,
  Smile,
  Meh,
  Frown,
  Video,
  Moon,
  Baby,
  Search,
  Users,
  Brain,
  Apple,
  Flower,
  Microscope,
  HelpCircle,
  Heart,
  Dna,
  FileText,
  Building,
  Waves,
  Book,
  CheckCircle2,
  TrendingUp,
  MapPin,
  Globe,
  MessageCircle,
  Shield,
  BarChart2,
  Stethoscope,
  Activity,
  School,
  AlertCircle,
  Check,
  X
} from 'lucide-react'

const EMOJI_TO_ICON = {
  '💊': Pill,
  '📊': BarChart3,
  '📋': ClipboardList,
  '✈️': Plane,
  '👤': User,
  '🎓': GraduationCap,
  '😊': Smile,
  '😐': Meh,
  '😟': Frown,
  '📹': Video,
  '🌙': Moon,
  '👶': Baby,
  '🔍': Search,
  '👨‍👩‍👧': Users,
  '🧠': Brain,
  '🥗': Apple,
  '🌸': Flower,
  '🔬': Microscope,
  '🤔': HelpCircle,
  '❤️': Heart,
  '🧬': Dna,
  '📄': FileText,
  '🏢': Building,
  '🏊': Waves,
  '📘': Book,
  '✅': CheckCircle2,
  '👨': User,
  '👩': User,
  '🧒': Baby,
  '🏫': School,
  '🛡': Shield,
  '🤱': Heart,
  '📈': TrendingUp,
  '📍': MapPin,
  '🌐': Globe,
  '💬': MessageCircle,
  '📺': Activity,
  '⚠': AlertCircle,
  '✓': Check,
  '✕': X,
}

const SERVICE_ID_TO_ICON = {
  'doctor-online': Video,
  'duty-doctor': Moon,
  'pediatrician': Baby,
  'second-opinion': Search,
  'family-doctor': Users,
  'psychologist': Brain,
  'dietician': Apple,
  'gynecologist': Flower,
  'analysis-understanding': Microscope,
  'medication-info': Pill,
  'symptom-checker': HelpCircle,
  'ecg-analysis': Heart,
  'mri-analysis': Dna,
  'health-diary': BarChart3,
  'sick-leave': FileText,
  'work-certificate': Building,
  'sports-certificate': Waves,
  'prescription': Pill,
  'medical-book': Book,
  'basic-checkup': CheckCircle2,
  'mens-checkup': User,
  'womens-checkup': User,
  'kids-checkup': Baby,
  'school-medicine': School,
  'child-health': Baby,
  'school-certificate': ClipboardList,
  'travel-medicine': Plane,
  'travel-insurance': Shield,
  'health-manager': User,
  'pregnancy-care': Heart,
  'chronic-care': TrendingUp,
}

export function getIconComponent(emojiOrId) {
  if (!emojiOrId) return null
  return EMOJI_TO_ICON[emojiOrId] || SERVICE_ID_TO_ICON[emojiOrId]
}

export function hasLucideIcon(emojiOrId) {
  return emojiOrId && (EMOJI_TO_ICON[emojiOrId] || SERVICE_ID_TO_ICON[emojiOrId])
}
